config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'static_pages/home'
  get 'static_pages/help'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  root 'application#hello'
  root 'static_pages#home'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email= email.downcase}
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format:{ with: VALID_EMAIL_REGEX },
  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user
    else
        render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user= User.new
  end

  def create
      @user= User.new(user_params)
      if @user.save
        log_in @user
        redirect_to root_url
      else
        render 'new'
      end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]=user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user=nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"
  <<div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EthnicGroups</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
</<!DOCTYPE html>
<style>
  html,body {
    height:100%;
    background: #FA8072;
  }

  .first {
    opacity: 0.5;
    width: 100%;
    height:100vh;
    min-height:100%;
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-image:url('https://lh3.googleusercontent.com/-rrAvRyhPa6I/XBx2HHxFzPI/AAAAAAAABn4/db5GdFsPdcEnUH931EzLdO9Sh88vZUdvwCJoC/w530-h377-n-rw/0918446dce2bb4a8ce133d35ef94003c.png');
    background-position: top center;
  }

  .affix {
    background-color: #441F30;
    -webkit-transition:padding 0.2s ease-out;
    -moz-transition:padding 0.2s ease-out;
    -o-transition:padding 0.2s ease-out;
    transition:padding 0.2s ease-out;
  }

  @media (min-width:768px) {
      .affix-top {
        /* navbar style at top */
        background-color:transparent;
        border-color:transparent;
        padding: 15px;
        -webkit-transition:all 0.5s ease;
        -moz-transition:all 0.5s ease;
        -o-transition:all 0.5s ease;
        transition:all 0.5s ease;
        background-attachment: scroll;
      }
  }

  nav .navbar-nav .nav-link,
  nav .navbar-brand {
     color: #fff;
  }

  .parallax-container{
    position: relative;
    overflow: visible;
    width: 100%;
    height: 395px;
  }

  .parallex-


</style>
<script>
  $(document).ready(function(){
    $(document).scroll(function(){
        var st = $(this).scrollTop();
        if(st > $('#services').offset().top) {
            $("nav").addClass('affix');
        } else {
            $("nav").removeClass('affix');
        }
    });
  });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<html lang="en" dir="ltr">
  <body>
    <nav id="nav" class="navbar fixed-top navbar-expand-sm" data-spy="affix">
    <div class="container">
        <a href="#" class="navbar-brand">Myanmar Ethnic Groups</a>
        <a class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">☰</a>
        <div class="navbar-collapse collapse">
            <!-- <ul class="navbar-nav">
                <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
            </ul> -->
            <ul class="ml-auto navbar-nav">
                <li class="nav-item"><a href="#" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link">About</a></li>
                <% if logged_in? %>
                  <li class="nav-item"><%= link_to "Users" , "#", class: "nav-link" %></li>
                  <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", '#' %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", signout_path, method: :delete %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                <li class="nav-item">
                  <!-- <a href="#" class="nav-link">Sign Up</a> -->
                  <%= link_to "Sign up", signup_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign in", signin_path, class: "nav-link" %>
                </li>
                <% end %>

                <!-- <li class="nav-item"><a href="#" class="nav-link"><span class="badge badge-pill text-white bg-dark">2</span></a></li> -->
            </ul>
        </div>
    </div>
</nav>
<!-- /.navbar -->
<section class="first">
    <div class="container"></div>
</section>
<section id="services">
  <div class="parallax-container">
    <div class="parallax-layer layer-0" data-parallax-speed="0.05" data-max-scroll="565"></div>
    <div class="parallax-layer layer-1" data-parallax-speed="0.1" data-max-scroll="565"></div>
    <div class="parallax-layer layer-2" data-parallax-speed="0.2" data-max-scroll="565"></div>
  </div>

  <div class="content">
    <h1>Alina Abidi</h1>
  </div>
</section>
<section>
    <div class="container">
        <h1>Here is some more content</h1>
    </div>
</section>
<section>
    <div class="container">
        <h1>Here is some more content</h1>
    </div>
</section>
  </body>
</html>

app/views/users/new.html.erb
<style>
  $button: rgba(148,186,101,0.7);
body {
  background: #384047;
  font-family: sans-serif;
  font-size: 10px
}
form {
  background: #fff;
  padding: 4em 4em 2em;
  max-width: 500px;
  margin: 50px auto;
  box-shadow: 0 0 1em #222;
  border-radius: 2px;
  h2 {
    margin:0 0 50px 0;
    padding:10px;
    text-align:center;
    font-size:30px;
    color:darken(#e5e5e5, 50%);
    border-bottom:solid 1px #e5e5e5;
  }
  p {
    margin: 0 0 3em 0;
    position: relative;
  }
  input {
    display: block;
    box-sizing: border-box;
    width: 100%;
    outline: none;
    margin:0;
  }
  input[type="text"],
  input[type="password"] {
    background: #fff;
    border: 1px solid #dbdbdb;
    font-size: 1.2em;
    padding: .8em .5em;
    border-radius: 2px;
  }
  input[type="text"]:focus,
  input[type="password"]:focus {
    background: #fff
  }
  span {
    display:block;
    background: #F9A5A5;
    padding: 2px 5px;
    color: #666;
  }
  input[type="submit"] {
    background: $button;
    box-shadow: 0 3px 0 0 darken($button, 10%);
    border-radius: 2px;
    border: none;
    color: #fff;
    cursor: pointer;
    display: block;
    font-size: 2em;
    line-height: 1.5em;
    margin: 2em 0 0;
    outline: none;
    padding: .8em 0;
    text-shadow: 0 1px #68B25B;
  }
  input[type="submit"]:hover {
    background: rgba(148,175,101,1);
    text-shadow:0 1px 3px darken($button, 30%);
  }
  input[type="submit"]:hover {

  }
  label{
    position: absolute;
    left: 8px;
    top: 12px;
    color: #999;
    font-size: 16px;
    display: inline-block;
    padding: 4px 10px;
    font-weight: 400;
    background-color: rgba(255,255,255,0);
    @include transition(color .3s, top .3s, background-color .8s);
    &.floatLabel{
      top: -11px;
      background-color: rgba(255,255,255,0.8);
      font-size: 14px;
    }
	}

}
</style>
<div class="signup">
      <%= form_for(@user) do |f| %>
      <h2>Sign Up</h2>

       <p>
        <%= f.label :name,  class: 'floatLabel'%>
        <%= f.text_field :name, class: 'form-control' %>
       </p>
        <p>
        <%= f.label :email, class: 'floatLabel'%>
        <%= f.email_field :email, class: 'form-control' %>
        </p>
        <p>
        <%= f.label :password, class: 'floatLabel'%>
        <%= f.password_field :password, class: 'form-control' %>
        </p>
        <p>
        <%= f.label :password_confirmation, "Confirmation", class: 'floatLabel'%>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        </p>
        <p>
        <%= f.submit "Create account" , class: 'btn btn-primary' %>
        </p>
      <% end %>

</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
        <%= gravatar_for @user %>
        <h1><%= @user.name %></h1>
        <span><%= @user.email %></span>
    </section>
  </aside>
</div>